print("Hi my name is dave")
name = input("What is your name?:")
print(f"Hi {name} how are you feeling today?")
emotion = input("")
print(f" what happened to make you feel {emotion} today?")
answer1 = input("")
print(f"So you feel {emotion} because you you {answer1} happppened today?")
input("")
rate = input("so how would you rate my conversation skill siklsl from 1-10 :")
rate = int(rate)
if rate >1 and rate <3:
    print(f" {rate} REALLY WHY? HOW DO I DESERVE THIS!!! answer bellow please")
    answer2 = input (":")
    print("I don't really care")
    print (f"BUUUUUUUUUT I don't like you soooooooo")
    math = input("you get to find the sum of 7!x2 =")
    math = int(math)
    if math == "10080":
        print("yes fine you did well...")
        print("wow you happen to be highly inteligent")
else:
    print("bye")
    print("go away")
    print("why are you still here?")
    whystillhere =  input("")
    print("thats a dumb reason")